<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ApertureITSM.Core\ApertureITSM.Core.csproj" />
    <ProjectReference Include="..\ApertureITSM.Infrastructure\ApertureITSM.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.17" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
